# Usa una base per Node.js per la build
FROM node:18 AS build

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file di progetto
COPY package.json package-lock.json ./ 
RUN npm install

COPY . .

# Costruisce l'app Angular
RUN npm run build --prod

# Usa un server Nginx per servire l'app
FROM nginx:alpine

# Copia i file buildati nella cartella di default di Nginx
COPY --from=build /app/dist/library-client-main/browser /usr/share/nginx/html

# Configura Nginx per Angular
RUN echo 'server { \
    listen 80; \
    server_name _; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

# Espone la porta 80
EXPOSE 80

# Comando di avvio di Nginx
CMD ["nginx", "-g", "daemon off;"]
